services:
  - type: web
    name: remote-config-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: remote-config-db
          property: connectionString

databases:
  - name: remote-config-db
    databaseName: remote_config
    user: remote_config_user
    plan: free 